# Generated by Django 6.0.2 on 2026-02-08 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('associados', '0004_rename_saldo_atual_associados_saldo_credito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(max_length=100)),
                ('data_evento', models.DateField()),
                ('local_evento', models.CharField(max_length=100)),
                ('valor_da_cota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('aberto', 'ABERTO'), ('cancelado', 'CANCELADO'), ('finalizado', 'FINALIZADO')], default='ABERTO', max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventoAssociacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_devido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('associacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='associados.associados')),
                ('eventos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='eventos.eventos')),
            ],
        ),
    ]
