# Generated by Django 6.0.2 on 2026-02-18 04:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Associados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('tipo', models.CharField(blank=True, choices=[('jogador', 'Jogador'), ('torcedor', 'Torcedor')], max_length=50, null=True)),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
                ('valor_mensalidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_credito', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('associacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.assoociacao')),
            ],
        ),
    ]
