# Generated by Django 6.0.2 on 2026-02-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='associados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('tipo', models.CharField(blank=True, choices=[('jogador', 'Jogador'), ('torcedor', 'Torcedos')], max_length=50, null=True)),
            ],
        ),
    ]
