# Generated by Django 6.0.2 on 2026-02-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='associados',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='associados',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='associados',
            name='saldo_atual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='associados',
            name='valor_mensalidade',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='associados',
            name='tipo',
            field=models.CharField(blank=True, choices=[('jogador', 'Jogador'), ('torcedor', 'Torcedor')], max_length=50, null=True),
        ),
    ]
