# Generated by Django 6.0.2 on 2026-02-05 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0002_associados_ativo_associados_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associados',
            name='data_cadastro',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
