# Generated by Django 6.0.2 on 2026-02-06 04:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0003_alter_associados_data_cadastro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='associados',
            old_name='saldo_atual',
            new_name='saldo_credito',
        ),
        migrations.AlterField(
            model_name='associados',
            name='data_cadastro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
