# Generated by Django 6.0.2 on 2026-02-06 04:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('associados', '0004_rename_saldo_atual_associados_saldo_credito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('ano', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('PAGA', 'Paga')], default='ABERTA', max_length=10)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensalidades', to='associados.associados')),
            ],
            options={
                'ordering': ['ano', 'mes'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateField(auto_now_add=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='associados.associados')),
            ],
        ),
        migrations.CreateModel(
            name='PagamentoMensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_utilizado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('mensalidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_relacionados', to='financeiro.mensalidade')),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensalidades_quitadas', to='financeiro.pagamento')),
            ],
        ),
        migrations.AddConstraint(
            model_name='mensalidade',
            constraint=models.UniqueConstraint(fields=('associado', 'mes', 'ano'), name='unique_mensalidade_por_mes'),
        ),
    ]
